# Generated by Django 4.2 on 2023-04-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteit', '0002_note_created_at_note_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_img',
            field=models.ImageField(blank=True, upload_to='img/'),
        ),
    ]
