# Generated by Django 4.2 on 2023-04-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteit', '0003_note_note_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_img',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
